# Generated by Django 4.0.3 on 2022-04-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='apellido')),
                ('fecha_nac', models.DateField(verbose_name='fecha_nac')),
                ('DNI', models.IntegerField(verbose_name='DNI')),
                ('edad', models.IntegerField(verbose_name='EDAD')),
            ],
        ),
    ]
