# Generated by Django 4.0.3 on 2022-04-06 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DesafioClase18', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiares',
            name='edad',
        ),
    ]
